[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "VLC"
authors = [{name = "Hermina", email = "herminial@l909.info"}]
dynamic = ["version", "description"]
